# Generated by Django 5.0 on 2024-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0007_codingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='subject',
            field=models.CharField(default='subject', max_length=200),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='test_level',
            field=models.CharField(default='testlevel', max_length=200),
        ),
    ]
