# Generated by Django 5.0 on 2024-01-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0010_alter_codingquestion_code_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='code_snippet',
            field=models.TextField(default='code_snipet'),
        ),
    ]
