# Generated by Django 5.0 on 2024-01-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0011_alter_codingquestion_code_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=250)),
                ('test_choosen', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap')], max_length=80)),
            ],
        ),
    ]
