# Generated by Django 5.0.1 on 2024-02-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0017_coding_questions_list_student_coding_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coding_questions_list',
        ),
    ]
