# Generated by Django 5.0.2 on 2024-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0022_user_register_register_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='loged_in',
            field=models.BooleanField(default=False),
        ),
    ]
