# Generated by Django 5.0.1 on 2024-03-02 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0023_user_register_loged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding_questions',
            name='subject',
            field=models.ForeignKey(blank=True, default=' ', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='mockapp.add_subjects'),
        ),
        migrations.CreateModel(
            name='Mcq_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testlevel', models.CharField(blank=True, choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500)),
                ('question', models.CharField(default=None, max_length=1000)),
                ('optionA', models.CharField(max_length=1000)),
                ('optionB', models.CharField(max_length=1000)),
                ('optionC', models.CharField(max_length=1000)),
                ('optionD', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('subject', models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='mockapp.add_subjects')),
            ],
        ),
    ]
