# Generated by Django 5.0.1 on 2024-03-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0025_remove_student_result_coding_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='code_snippet',
            field=models.TextField(blank=True, default=' ', help_text='Enter your Programming answer here.'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='correct_answer',
            field=models.TextField(blank=True, default=' ', help_text='Enter your Theory answer here.'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_text',
            field=models.TextField(blank=True, default='', help_text='Enter your Question here.'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='subject',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap')], default=' ', help_text='Choose Subject.', max_length=200),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='test_level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default=' ', help_text='Choose test level.', max_length=200),
        ),
    ]
