# Generated by Django 5.0.1 on 2024-03-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0026_alter_codingquestion_code_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding_questions',
            name='code_snippet',
            field=models.TextField(blank=True, default=' ', help_text='Enter your Programming answer here.'),
        ),
        migrations.AlterField(
            model_name='coding_questions',
            name='correct_answer',
            field=models.TextField(blank=True, default=' ', help_text='Enter your Theory answer here.'),
        ),
        migrations.AlterField(
            model_name='coding_questions',
            name='question_text',
            field=models.TextField(blank=True, default='', help_text='Enter your Question here.'),
        ),
        migrations.AlterField(
            model_name='coding_questions',
            name='test_level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default=' ', help_text='Choose test level.', max_length=200),
        ),
    ]
