# Generated by Django 5.0.2 on 2024-03-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0027_alter_coding_questions_code_snippet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestionsAllow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='basic', max_length=100)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('coding_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.add_subjects')),
            ],
            options={
                'unique_together': {('coding_sub', 'test_level')},
            },
        ),
        migrations.CreateModel(
            name='QuestionsAllow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='basic', max_length=100)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.add_subjects')),
            ],
            options={
                'unique_together': {('sub', 'tl')},
            },
        ),
    ]
