# Generated by Django 5.0.1 on 2024-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0028_codingquestionsallow_questionsallow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
