# Generated by Django 5.0 on 2023-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0002_bootstrap_css_html_java_javascript_python'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='css',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='html',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='java',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='python',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'intermediate'), ('advance', 'Advance')], max_length=500),
        ),
    ]
