# Generated by Django 5.0 on 2023-12-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0003_alter_bootstrap_testlevel_alter_css_testlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaddocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap')], max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='bootstrap',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='css',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='html',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='java',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500),
        ),
        migrations.AlterField(
            model_name='python',
            name='testlevel',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=500),
        ),
    ]
