# Generated by Django 5.0 on 2023-12-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0004_uploaddocument_alter_bootstrap_testlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='java',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='javascript',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='python',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
