# Generated by Django 5.0 on 2023-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0005_html_question_java_question_javascript_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='css',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
