# Generated by Django 5.0 on 2024-01-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0009_alter_codingquestion_code_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='code_snippet',
            field=models.TextField(default=None),
        ),
    ]
