# Generated by Django 5.0.2 on 2024-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0020_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_subjects',
            name='sub_image',
            field=models.ImageField(default=' ', upload_to='subject_images/'),
        ),
    ]
