# Generated by Django 5.0.2 on 2024-02-18 19:41

import mockapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0021_add_subjects_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='register_id',
            field=models.CharField(default=mockapp.models.generate_register_id, max_length=100),
        ),
    ]
